org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.ndk.suppressMinSdkVersionError=21
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

android.ndkVersion=26.2.11394342
