// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5rzuZ429Fo-QN1sMbOuH_KHS4xlUP2R0',
    appId: '1:532909089194:web:d048989203cd8e23148bd3',
    messagingSenderId: '532909089194',
    projectId: 'tranoo',
    authDomain: 'tranoo.firebaseapp.com',
    storageBucket: 'tranoo.firebasestorage.app',
    measurementId: 'G-JHQLMNPR2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGyKoZRckr8JoRvyDN-pMJ0e3UJY7a4h8',
    appId: '1:532909089194:android:a17e023f3043ef51148bd3',
    messagingSenderId: '532909089194',
    projectId: 'tranoo',
    storageBucket: 'tranoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvYGvPDNdsGF-NB0snjFdzQ8pS8-y1GQ',
    appId: '1:532909089194:ios:a0ddc26ce53de965148bd3',
    messagingSenderId: '532909089194',
    projectId: 'tranoo',
    storageBucket: 'tranoo.firebasestorage.app',
    iosBundleId: 'com.example.tranoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5rzuZ429Fo-QN1sMbOuH_KHS4xlUP2R0',
    appId: '1:532909089194:web:1c8a730608bc45c8148bd3',
    messagingSenderId: '532909089194',
    projectId: 'tranoo',
    authDomain: 'tranoo.firebaseapp.com',
    storageBucket: 'tranoo.firebasestorage.app',
    measurementId: 'G-JDM6DPGE0H',
  );
}
